### ISSUE TITLE
Crash on save in VAB

### ISSUE THREAD

**Issue by arrowmaster** [linuxgurugamer/AutoQuickSaveSystem#1]
WIth the option to save VAB/SPH ships in the editors on a schedule enabled. This mod can consistently crash the game.

Steps to reproduce.
1. Enable automatic ship saving in editor
2. Create new ship and add root part
3. Delete root part
4. Wait for next save

**Comment by linuxgurugamer** [comment]
Seems like an edge case, I'll get it fixed in the next few days

**Comment by linuxgurugamer** [comment]
Would have been nice if you provided a log file

**Comment by linuxgurugamer** [comment]
Note, this will happen even if automatic ship saving in editor is not enabled.

**Comment by linuxgurugamer** [comment]
Not this mod

Edit: Actually, it might be, see below

**Comment by linuxgurugamer** [comment]
Do you have QuickStart installed?  This uses the same code as QuickStart, may have been hiding the issue in my tests

**Comment by linuxgurugamer** [comment]
It is the same error in both mods, will be fixed later this evening

**Comment by linuxgurugamer** [comment]
Fixed and released

**Comment by arrowmaster** [comment]
Thank you. I literally just finished making a separate copy of the game with only AQSS installed to try and get you logs when I saw the email notification. You were faster than I was.
